version: "3"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    restart: always
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - RAILS_ENV=production
        - BUNDLE_WITHOUT=development:test
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/honestbee_interview_test
    environment:
      - RAILS_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
