version: "3"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/honestbee_interview_test
    ports:
      - 3000
    depends_on:
      - db
