version: "3"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/honestbee_interview_test
    ports:
      - "3000:3000"
    depends_on:
      - db
