version: "3"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432
  app:
    build:
      context: .
      args:
        - RAILS_ENV=test
        - BUNDLE_WITHOUT=production
    volumes:
      - .:/honestbee_interview_test
    environment:
      - RAILS_ENV=test
    ports:
      - 3000
    depends_on:
      - db
