apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: honestbee-interview-test
spec:
  type: LoadBalancer
  loadBalancerIP: 35.185.138.84
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    run: app
