apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: honestbee-interview-test
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30390
      targetPort: 3000
  selector:
    run: app
