apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rails-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: app
              servicePort: 3000
            path: /
